<?php
$defaultLocale = $this->localization()->getDefaultLocale();
$availableLocales = [];
foreach ($this->localization()->getAvailableLocalesDisplay() as $locale => $localeDisplay) {
    if(!$this->permission('admin42')->isGranted('sitemap/locale/' . $locale)) continue;

    $availableLocales[$locale] = $localeDisplay;
}

if (!in_array($defaultLocale, array_keys($availableLocales))) {
    $defaultLocale = key($availableLocales);
    reset($availableLocales);
}
?>

<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="<?= $this->icon?>"></span> <?= $this->label ?>
    </h1>
</div>
<div class="wrapper-md" ng-controller="FlatController" ng-init="flat.locale = '<?= $defaultLocale ?>'" add-url="<?= $this->url($this->routes['add-sitemap'])?>">
    <div class="panel panel-default">
        <div class="table-responsive" ng-controller="DataGridController" data-url="<?= $this->url()?>" persist="<?= md5($this->routes['index']) ?>">
            <table st-table="collection"  st-pipe="callServer" st-refresh class="table table-striped top-border-radius">
                <thead>
                <tr>
                    <th width="5%" st-sort="id"><?= $this->translate('field.id', 'admin') ?></th>
                    <th st-sort="name">Name</th>
                    <th width="8%">Status</th>
                    <th width="15%" st-sort="publishedFrom">Published From</th>
                    <th width="15%" st-sort="publishedUntil">Published Until</th>
                    <th width="15%"></th>
                </tr>
                <tr>
                    <th>
                        <input st-search="frontend42_page.id" class="form-control input-sm" type="text"/>
                    </th>
                    <th>
                        <input st-search="name" placeholder="<?= $this->translate('search.name', 'admin') ?>" class="form-control input-sm" type="text"/>
                    </th>
                    <th>
                        <select class="form-control" st-input-event="change" st-search42="status">
                            <option value="online">Online</option>
                            <option value="offline">Offline</option>
                        </select>
                    </th>
                    <th colspan="2"></th>
                    <th>
                        <select class="form-control" st-input-event="change" st-search42="locale" ng-model="flat.locale">
                            <?php foreach ($availableLocales as $locale => $localeDisplay): ?>
                                <option value="<?= $locale ?>"><?= $localeDisplay ?></option>
                            <?php endforeach ?>
                        </select>
                    </th>
                </tr>
                </thead>
                <tbody ng-hide="isLoading">
                <tr ng-repeat="row in collection">
                    <td class="text-right vertical-middle"><code>#{{row.id}}</code></td>
                    <td class="vertical-middle">
                        <span ng-if="row.name.length > 0">{{row.name}}</span>
                        <span ng-if="row.alternateNames.length > 0">
                            <small ng-repeat="alternatives in row.alternateNames" style="color:#888888;">
                                [ <i class="flag-icon flag-icon-{{ alternatives.region }}"></i> <del>{{ alternatives.title }}</del> ]
                            </small>
                        </span>

                    </td>
                    <td class="vertical-middle">
                        <span class="label" ng-class="{'label-success': row.status == 'online', 'label-danger': row.status == 'offline'}">{{ row.status }}</span>
                    </td>
                    <td class="vertical-middle"><small>{{row.publishedFrom | datetime}}</small></td>
                    <td class="vertical-middle"><small>{{row.publishedUntil | datetime}}</small></td>

                    <td class="text-right vertical-middle">
                        <?php if($this->permission('admin42')->isGranted('route/' . $this->routes['edit'])): ?>
                        <a class="btn btn-info btn-xs" ng-href="<?= $this->url($this->routes['edit'], ['id' => '{{ row.id }}']) ?>">
                            <span class="fa fa-pencil"></span>
                        </a>
                        <?php endif; ?>
                        <?php if($this->permission('admin42')->isGranted('route/' . $this->routes['delete'])): ?>
                        <delete
                            url="<?= $this->url($this->routes['delete']) ?>"
                            title="<?= $this->translate("sitemap.modal.delete.title", "admin") ?>"
                            size="xs"
                            content="<?= $this->translate("sitemap.modal.delete.content", "admin") ?>"
                            request-id="{{row.sitemapId}}"
                            method="post"
                            >
                        </delete>
                        <?php endif; ?>
                    </td>
                </tr>
                </tbody>
                <tbody ng-show="isLoading">
                <tr>
                    <td colspan="6" class="text-center"><i class="fa fa-spin fa-refresh"></i></td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="6" class="text-center">
                        <div st-pagination="" st-items-by-page="10" st-displayed-pages="10"></div>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="panel-footer">
            <?php if($this->permission('admin42')->isGranted('route/' . $this->routes['add-sitemap'])): ?>
            <a class="btn btn-default" ng-click="addPage()">
                <span class="fa fa-plus-circle"></span>
                <?= $this->translate('button.page-add', 'admin') ?>
            </a>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php
$templateContent = <<<EOT
<div class="modal-header">
    <h3 class="modal-title">Add Page</h3>
</div>
<div class="modal-body">
    <div class="container-fluid">
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">
                    Name <abbr title="required">*</abbr>
                 </label>
                <div class="col-sm-10">
                    <input type="text" name="name" required="required" class="form-control" id="name" data-ng-model="formElement.name" data-ng-initial="" value="">
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-click="ok()">
        <span class="fa fa-plus-circle"></span>
        {$this->translate('button.page-add', 'admin')}
    </button>
    <button class="btn btn-default" ng-click="cancel()">{$this->translate('button.cancel', 'admin')}</button>
</div>
EOT;
$this->angular()->addHtmlTemplate("addFlatModalContent.html", $templateContent);
?>
