<div class="hbox hbox-auto-xs" ng-init="app.appContentFull = true">
    <div class="col">
        <div class="vbox">
            <div class="wrapper-md bg-white b-b">
                <h1 class="m-n font-thin h3">
                    <i class="flag-icon flag-icon-<?= strtolower(\Locale::getRegion($this->page->getLocale()))?>"></i>
                    <?= $this->translate('title.edit-sitemap', 'admin') ?>
                    <?php if (strlen($this->page->getName())): ?>
                        : "<?= $this->page->getName() ?>"
                    <?php endif; ?>
                    <a class="btn btn-default" href="<?= $this->url($this->routes['preview'], ['id' => $this->page->getId()])?>" target="_blank">
                        <i class="fa fa-mail-forward"></i>
                    </a>
                </h1>
            </div>

            <?php if($this->versions->count() > 2 && $this->versions->current()->getApproved() === null): ?>
            <div class="alert alert-warning">
                <?= $this->translate('alert.unpublished-version', 'admin') ?>
            </div>
            <?php endif; ?>
            <?php $this->versions->rewind() ?>

            <div class="row-row">

                <div class="wrapper-md">

                    <?php if (count($this->pageForm->getMessages())): ?>
                        <?php foreach ($this->pageForm->getMessages() as $fieldsetName => $fields): ?>
                            <?php $fieldset = $this->pageForm->get($fieldsetName) ?>
                            <?php foreach ($fields as $fieldName => $messages): ?>
                                <?php $field = $fieldset->get($fieldName) ?>
                                <?php foreach ($messages as $message): ?>
                                    <div class="alert alert-danger">
                                        <?= $field->getLabel() ?> in <?= $this->translate($fieldset->getLabel(), 'admin') ?> Tab: <?= $message ?>
                                    </div>
                                <?php endforeach ?>
                            <?php endforeach ?>
                        <?php endforeach ?>
                    <?php endif ?>

                    <form class="form-horizontal" action="<?= $this->url(null, [], [], true)?>" method="post">
                        <uib-tabset uib-tabset-persist="<?= md5($this->url(null, [], [], true)) ?>" class="tab-container">
                            <?php
                            $this->pageForm->prepare();
                            ?>
                            <?php foreach ($this->pageForm as $fieldset): ?>
                                <uib-tab class="<?= count($fieldset->getMessages()) ? 'has-errors' : '' ?>">
                                    <uib-tab-heading>
                                        <?= $this->translate($fieldset->getLabel(), 'admin') ?>
                                    </uib-tab-heading>
                                    <?= $this->formCollection($fieldset) ?>
                                </uib-tab>
                            <?php endforeach; ?>
                        </uib-tabset>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <button class="btn btn-success" type="submit" name="save" value="save">
                                    <span class="fa fa-save"></span>
                                    <?= $this->translate('button.save', 'admin') ?>
                                </button>
                                <button class="btn btn-success" type="submit" name="save" value="approve">
                                    <span class="fa fa-save"></span>
                                    <?= $this->translate('button.save-approve', 'admin') ?>
                                </button>
                                <delete
                                    url="<?= $this->url($this->routes['delete']) ?>"
                                    title="<?= $this->translate("sitemap.modal.delete.title", "admin") ?>"
                                    content="<?= $this->translate("sitemap.modal.delete.content", "admin") ?>"
                                    request-id="<?= $this->page->getSitemapId() ?>"
                                    >
                                </delete>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col w-md lter b-l bg-light">
        <div class="vbox">
            <div class="wrapper-md b-b">
                <div class="m-n font-thin h3">Information</div>
            </div>
            <div class="row-row">
                <div class="wrapper-md">
                    <div class="tl-header">
                        <div class="b-a b-l bg-white text-left m-b-md">
                            <div class="wrapper-xs">
                                <div class="text-center">
                                    <?php foreach ($this->localization()->getAvailableLocalesDisplay() as $locale => $displayName): ?>
                                        <?php if ($this->page->getLocale() == $locale) continue; ?>
                                        <a href="<?= $this->url($this->routes['change-language'], ['locale' => $locale, 'sitemapId' => $this->page->getSitemapId()]) ?>" title="<?= $displayName ?>">
                                            <i class="flag-icon flag-icon-<?= strtolower(\Locale::getRegion($locale))?> m-r-xs"></i>
                                        </a>
                                    <?php endforeach; ?>
                                    <div class="line line-dashed b-b line-lg"></div>
                                </div>
                                <div class="text-center"
                                     ng-controller="ChangePageTypeController"
                                     change-url="<?= $this->url($this->routes['change-page-type'], ['pageId' => $this->page->getId(), 'sitemapId' => $this->page->getSitemapId()]) ?>">
                                    <button class="btn btn-default btn-sm" type="button" ng-click="change()">
                                        <?= $this->translate('button.change-pageType', 'admin') ?>
                                    </button>
                                </div>

                            </div>
                        </div>
                    </div>

                    <ul class="timeline timeline-sidebar">
                        <li class="tl-header">
                            <div class="b-a b-l bg-white text-left">
                                <dl class="wrapper-xs">
                                    <dt>Created</dt>
                                    <dd><?= $this->page->getCreated()->format("Y-m-d H:i:s") ?></dd>
                                    <dt>Last Modified</dt>
                                    <dd><?= $this->page->getUpdated()->format("Y-m-d H:i:s") ?></dd>
                                    <dt>Created By</dt>
                                    <dd><?= $this->admin()->getUserDisplayNameById($this->page->getCreatedBy()) ?></dd>
                                </dl>
                            </div>
                        </li>
                        <?php if ($this->versions->count() > 0) :?>
                        <?php foreach ($this->versions as $version): ?>
                            <li class="tl-item">
                                <div class="tl-wrap <?= $version->getId()!== $this->currentVersion->getId() ? 'b-dark' : 'b-primary' ?>">
                                    <span class="tl-date text-xs">
                                        <div>
                                            <span class="shortname-container-xs" popover-trigger="mouseenter" popover-placement="left" popover="<?= $this->admin()->getUserDisplayNameById($version->getCreatedBy()) ?>">
                                                <?= $this->admin()->getUserShortNameNameById($version->getCreatedBy()) ?>
                                            </span>
                                        </div>
                                        <div class="m-t-xs">
                                            <?= $version->getCreated()->format("Y-m-d H:i:s") ?>
                                        </div>
                                    </span>
                                    <div class="tl-content b-a panel<?= $version->getId() !== $this->currentVersion->getId() ? '' : ' bg-primary' ?>" style="padding: 5px; 2px; width: 5em;">
                                        <span class="arrow left pull-up<?= $version->getId() !== $this->currentVersion->getId() ? '': ' arrow-primary' ?>"></span>
                                        <div>
                                            <code class="text-xs">#<?= $version->getVersionId() ?></code>
                                        </div>
                                        <div class="center-block m-t-xs text-dark">
                                            <a popover-trigger="mouseenter" popover-placement="top" popover="Load Version" class="btn btn-default btn-xs" href="<?= $this->url(null, ['version' => $version->getVersionId()], [], true)?>">
                                                <span class="fa fa-check-circle-o"></span>
                                            </a>
                                            <?php if ($version->getApproved() === null): ?>
                                            <a popover-trigger="mouseenter" popover-placement="top" popover="Approve" class="btn btn-default btn-xs" href="<?= $this->url($this->routes['approve'], ['id' => $this->page->getId(), 'version' => $version->getVersionId()]) ?>">
                                                <span class="fa fa-thumbs-up"></span>
                                            </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach; ?>
                        <?php endif; ?>

                        <li class="tl-header">
                            <span class="bg-white b-a">
                                <i class="fa fa-crosshairs"></i>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<?php
$modalContent = <<<EOT
<div class="modal-header">
    <h3 class="modal-title">{$this->translate('sitemap.modal.change-page-type.title', 'admin')}</h3>
</div>
<div class="modal-body">
    <div class="container-fluid">
        <div class="m-b-md">
            {$this->translate('sitemap.modal.change-page-type.content', 'admin')}
        </div>
        <form class="form-horizontal" role="form">
            {$this->form($this->changePageTypeForm)}
        </form>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-danger" ng-click="ok()">
        {$this->translate('button.change-pageType', 'admin')}
    </button>
    <button class="btn btn-default" ng-click="cancel()">{$this->translate('button.cancel', 'admin')}</button>
</div>
EOT;

$this->admin()->addHtmlTemplate("changePageTypeModal.html", $modalContent);
?>
