<div class="hbox hbox-auto-xs" ng-init="app.appContentFull = true">
    <div class="col">
        <div class="vbox">
            <div class="wrapper-md bg-white b-b">
                <h1 class="m-n font-thin h3">
                    <span class="fa fa-sitemap"></span>
                    <?= $this->translate('title.edit-sitemap', 'admin') ?>
                </h1>
            </div>
            <div class="row-row">
                <div class="wrapper-md">
                    <form class="form-horizontal" action="<?= $this->url(null, [], [], true)?>" method="post">
                        <tabset class="tab-container">
                            <?php
                            $this->pageForm->prepare();
                            ?>
                            <?php foreach ($this->pageForm as $fieldset): ?>
                                <tab>
                                    <tab-heading>
                                        <?= $this->translate($fieldset->getLabel(), 'admin') ?>
                                    </tab-heading>
                                    <?= $this->formCollection($fieldset) ?>
                                </tab>
                            <?php endforeach; ?>
                        </tabset>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <button class="btn btn-success" type="submit">
                                    Save
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col w-md lter b-l bg-light">
        <div class="vbox">
            <div class="wrapper-md b-b">
                <div class="m-n font-thin h3">Information</div>
            </div>
            <div class="row-row">
                <div class="wrapper-md">
                    <ul class="timeline timeline-sidebar">
                        <li class="tl-header">
                            <div class="b-a b-l bg-white text-left">
                                <dl class="wrapper-xs">
                                    <dt>Created</dt>
                                    <dd>2015-01-01 12:12:12</dd>
                                    <dt>Last Modified</dt>
                                    <dd>2015-01-01 12:12:12</dd>
                                    <dt>Created By</dt>
                                    <dd>Thomas Payer</dd>
                                </dl>
                            </div>
                        </li>
                        <?php if ($this->versions->count() > 0) :?>
                        <?php foreach ($this->versions as $version): ?>
                            <li class="tl-item">
                                <div class="tl-wrap <?= $version->getId()!== $this->currentVersion->getId() ? 'b-dark' : 'b-primary' ?>">
                                    <span class="tl-date text-xs">
                                        <?= $version->getCreated()->format("Y-m-d H:i:s") ?>
                                    </span>
                                    <div class="tl-content b-a panel<?= $version->getId() !== $this->currentVersion->getId() ? '' : ' bg-primary' ?>" style="padding: 5px; 2px;">
                                        <span class="arrow left pull-up<?= $version->getId() !== $this->currentVersion->getId() ? '': ' arrow-primary' ?>"></span>
                                        <a class="text-xs" href="<?= $this->url(null, ['version' => $version->getVersionId()], [], true)?>">

                                            <code>#<?= $version->getVersionId() ?></code>
                                            <br>
                                            Thomas Payer
                                        </a>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach; ?>
                        <?php endif; ?>

                        <li class="tl-header">
                            <span class="bg-white b-a">
                                <i class="fa fa-crosshairs"></i>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
