<?php
$this->form->prepare();
?>


<form class="form-horizontal" role="form" action="<?= $this->url(null, array(), array(), true) ?>" method="post">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                <span class="fa fa-user"></span>
                <?= $this->translate('title.tree-add', 'admin')?>
            </h1>
        </div>
        <div class="panel-body">
            <?= $this->formRender($this->form)?>
        </div>
        <div class="panel-footer">
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-save"></span>
                        <?= $this->translate('button.save', 'admin') ?>
                    </button>

                    <a href="<?= $this->url('admin/tree') ?>" class="btn btn-default">
                        <?= $this->translate('button.cancel', 'admin') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>
