<?php
$this->form->prepare();
?>
<div style="margin-bottom: 10px;">
    <div class="pull-right">
        <?php
        $localeList = $this->locale()->getLocaleArray();
        ?>
        <?php if (count($localeList) == 1): ?>
            <input id="languageSelection" type="hidden" value="<?= current(array_keys($localeList)) ?>">
        <?php else: ?>
            <select id="languageSelection" class="form-control input-sm">
                <?php foreach($localeList as $locale => $display): ?>
                    <option value="<?= $locale ?>"<?= ($locale == $this->locale) ? " selected": ""?>><?= $display ?></option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
    <div class="clearfix"></div>
</div>
<form class="form-horizontal" role="form" action="<?= $this->url(null, array(), array(), true) ?>" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                <span class="fa fa-user"></span>
                General Settings
            </h1>
        </div>
        <div class="panel-body">


            <div class="panel panel-default">
                <div class="panel-body">
                    <?= $this->formRender($this->form->get('page'))?>
                </div>
            </div>

            <?php if ($this->form->has('elementFields')): ?>

            <hr>

            <div class="panel-group">
                <?php foreach($this->form->get('elementFields') as $element): ?>
                    <?php
                    $id = $element->getName();
                    $webSaveId = str_replace("]", "", str_replace("[", "", $id));
                    ?>
                <div id="panel_<?= $webSaveId ?>" class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title pull-left">
                            <a data-toggle="collapse" href="#content_<?= $webSaveId ?>">
                                <span class="fa fa-chevron-down fa-fw"></span>
                                Content
                            </a>
                        </h4>
                        <div class="pull-right">
                            <?php if (false): ?>
                            <a href="#panel_<?= $id ?>" class="btn btn-danger btn-xs delete-handle">
                                <span class="fa fa-trash-o fa-fw"></span>
                            </a>
                            <a class="btn btn-info btn-xs sortable-handle">
                                <span class="fa fa-sort fa-fw"></span>
                            </a>
                            <?php endif; ?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div id="content_<?= $webSaveId ?>" class="panel-collapse collapse">
                        <div class="panel-body">
                            <input type="hidden" name="<?= $id ?>[order]" value="">
                            <input type="hidden" name="<?= $id ?>[delete]" value="0">
                            <?= $this->formRender($element) ?>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

                <div class="pull-right">
                    <button type="button" class="btn btn-default" id="add-element">
                        Add Content
                    </button>
                </div>
            <?php endif; ?>

        </div>
        <div class="panel-footer">
            <div class="form-group">
                <div class="col-sm-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-save"></span>
                        <?= $this->translate('button.save', 'admin') ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

<script>
    (function ($) {
        var $this;
        var items;
        var settings = {
            itemHandle: '.panel',
            sortableHandle: '.sortable-handle',
            deleteHandle: '.delete-handle',
            orderField: 'input[type=hidden][name^=elementFields][name$=\\[order\\]]',
            deleteField: 'input[type=hidden][name^=elementFields][name$=\\[delete\\]]'
        };

        $.fn.elementFields = function(){
            $this = this;
            items = $this.children(settings.itemHandle);

            $this.sortable({
                handle: settings.sortableHandle,
                stop: function(event, ui) {
                    items = $(this).children(settings.itemHandle);
                    sortElements();
                }
            });

            $(settings.deleteHandle).on('click', $this, deleteElement);
            $('#add-element').on('click', $this, addElement);

            return $this;
        };

        function sortElements(){
            var order = 0;
            $.each(items, function(index, value){
                var deletedInput = $(settings.deleteField, value);
                if (deletedInput.val() == 1) {
                    $(settings.orderField, value).val(-1);
                    return;
                }

                $(settings.orderField, value).val(order);
                order++;
            });
        };

        function deleteElement(event){
            event.preventDefault();

            var panel = $($(this).attr('href'), $this);

            var deletedInput = $(settings.deleteField, panel);

            if (deletedInput.val() == 0) {
                panel.removeClass('panel-default').addClass('panel-danger');
                deletedInput.val(1);
            } else {
                panel.removeClass('panel-danger').addClass('panel-default');
                deletedInput.val(0);
            }

            sortElements();
        };

        function addElement(event){
            event.preventDefault();

            var url= '<?= $this->url('admin/tree/add-element') ?>';
            $.get(url, function( data ) {
                $this.append(data);

                sortElements();
            });
        };
    } (jQuery));

    <?php
    $urls = array();
    foreach (array_keys($localeList) as $locale) {
        $urls[$locale] = $this->url('admin/tree/edit', array('locale' => $locale, 'id' => $this->params()->fromRoute('id')));
    }
    ?>
    var urls = <?= json_encode($urls) ?>;

    $(document).ready(function(){
        $('.panel-group').elementFields();

        $('#languageSelection').change(function(){
            var url = urls[$(this).val()];
            document.location.href = url;
        });
    });
</script>
