<div id="jstree"></div>
<script type="application/javascript">
    var jsTree = null;
    var url = '<?= $this->url('admin/tree/json', array('locale' => $this->locale)); ?>'

    var createTree = function() {
        jsTree = $('#jstree').jstree({
            "core": {
                "check_callback" : true,
                "data": {
                    "url": url
                }
            },
            "plugins" : ["types"]
        }).bind("select_node.jstree", function (e, data) {
            document.location.href = data.node.a_attr.href
        });
    };

    $(document).ready(function(){
        createTree();
    });
</script>
