<?php if($this->permission('admin42')->isGranted('route/' . $this->routes['save'])): ?>
<div class="dd-handle dd3-handle" ui-tree-handle>&nbsp;</div>
<?php endif; ?>
<div class="dd3-content"<?= ($this->permission('admin42')->isGranted('route/' . $this->routes['save'])) ? '' : ' style="padding-left:5px;"' ?>>
    <div class="row">
        <div class="col-sm-6">
            <a ng-if="item.items.length > 0" class="btn btn-link btn-xs" ng-click="toggle(this)">
                <span class="glyphicon text-muted" ng-class="{'glyphicon-chevron-right': collapsed, 'glyphicon-chevron-down': !collapsed}"></span>
            </a>
            <code>#{{item.pageId}}</code>
            <span ng-if="item.title.length > 0" ng-bind-html="item.title | highlight: query"></span>
            <span ng-if="item.alternateNames.length > 0">
                <small ng-repeat="alternatives in item.alternateNames" style="color:#888888;">
                    [ <i class="flag-icon flag-icon-{{ alternatives.region }}"></i> <del>{{ alternatives.title }}</del> ]
                </small>
            </span>
        </div>
        <div class="col-sm-3 text-right">
            <span class="label label-default">{{ item.pageType }}</span>
            <span class="label" ng-class="{'label-success': item.status == 'online', 'label-danger': item.status == 'offline'}">{{ item.status }}</span>
        </div>
        <div class="col-sm-3 text-right">
            <?php if($this->permission('admin42')->isGranted('route/' . $this->routes['add-sitemap'])): ?>
            <a ng-if="item.droppable" class="btn btn-default btn-xs" ng-click="addSubPage(item.pageId)">
                <span class="fa fa-plus"></span>
            </a>
            <?php endif; ?>
            <?php if($this->permission('admin42')->isGranted('route/' . $this->routes['edit'])): ?>
            <a class="btn btn-info btn-xs" ng-href="<?= $this->url($this->routes['edit'], ['id' => '{{ item.pageId }}']) ?>">
                <span class="fa fa-pencil"></span>
            </a>
            <?php endif; ?>
            <?php if($this->permission('admin42')->isGranted('route/' . $this->routes['delete'])): ?>
            <delete
                url="<?= $this->url($this->routes['delete']) ?>"
                title="<?= $this->translate("sitemap.modal.delete.title", "admin") ?>"
                size="xs"
                content="<?= $this->translate("sitemap.modal.delete.content", "admin") ?>"
                request-id="{{item.id}}"
                method="delete"
                callback="deleteCallback"
            </delete>
            <?php endif; ?>
            <?php if($this->permission('admin42')->isGranted('route/' . $this->routes['preview'])): ?>
            <a class="btn btn-default btn-xs" ng-href="<?= $this->url($this->routes['preview'], ['id' => '{{ item.pageId }}']) ?>" target="_blank">
                <span class="fa fa-mail-forward"></span>
            </a>
            <?php endif; ?>
        </div>
    </div>
</div>
<ol class="dd-list" ui-tree-nodes="" ng-model="item.items" ng-class="{hidden: collapsed}"<?= (!$this->permission('admin42')->isGranted('route/' . $this->routes['save'])) ? ' data-nodrag' : '' ?>>
    <li class="dd-item dd3-item" ng-repeat="item in item.items" ui-tree-node ng-include="'nodes_renderer.html'" ng-show="visible(item)"></li>
</ol>
