<?php
$langOptions = [];
foreach($this->localization()->getAvailableLocalesDisplay() as $_locale => $_name){
    $langOptions[] = "<option value=\"{$_locale}\">{$_name}</option>";
}
$langOptions = implode(PHP_EOL, $langOptions);

$templateContent = <<<EOT
<div ng-controller="LinkSitemapController" data-active-locale="{$this->localization()->getDefaultLocale()}" data-request-url="{$this->url('admin/sitemap/list')}">
<div class="row">
<div class="col-md-3 col-md-offset-9">
    <select ng-model="locale" class="form-control" ng-change="loadTree()">
        {$langOptions}
    </select>
</div>
</div>
<div ng-show="isLoading" class="angular-ui-tree-loading text-center">
    <i class="fa fa-spin fa-refresh"></i>
</div>
<div ng-hide="isLoading" class="dd" ui-tree="treeOptions" data-drag-enabled="false">
    <ol class="dd-list" ui-tree-nodes="" ng-model="sitemap" id="tree-root">
        <li class="dd-item dd3-item" ng-repeat="item in sitemap" ui-tree-node ng-include="'linkSitemapNode.html'"></li>
    </ol>
</div>
</div>
EOT;
$this->admin()->addHtmlTemplate("/link/sitemap.html", $templateContent);

$sitemapContent = <<<EOT
<div class="dd3-content" style="padding-left:10px;" ng-style="selectableStyle(item)" ng-click="select(item)">
    <div class="row">
        <div class="col-md-10">
            <code>#{{item.pageId}}</code> {{item.title}}
        </div>
        <div class="col-md-2 text-right">
            <span ng-if="targetPageId == item.pageId" class="fa fa-check"></span>
        </div>
    </div>
</div>
<ol class="dd-list" ui-tree-nodes="" ng-model="item.items" ng-class="{hidden: collapsed}">
    <li class="dd-item dd3-item" ng-repeat="item in item.items" ui-tree-node ng-include="'linkSitemapNode.html'"></li>
</ol>
EOT;
$this->admin()->addHtmlTemplate("linkSitemapNode.html", $sitemapContent);