<?php
$defaultLocale = $this->localization()->getDefaultLocale();
$availableLocales = $this->localization()->getAvailableLocalesDisplay();
if (!array_key_exists($defaultLocale, $availableLocales)) {
    reset($availableLocales);
    $defaultLocale = key($availableLocales);
}
?>

<div ng-controller="SitemapLinkController" data-active-locale="<?= $this->localization()->getDefaultLocale() ?>" data-request-url="<?= $this->url('admin/sitemap/list') ?>">
    <div class="row">
        <div class="col-sm-<?= (count($availableLocales) > 1 ? "9" : "12")?>">
            <input placeholder="Search for Pages" class="form-control" type="text" ng-model="query" ng-change="findNodes()">
        </div>
        <?php if (count($availableLocales) > 1): ?>
        <div class="col-sm-3">
            <select ng-model="locale" class="form-control" ng-change="loadTree()">
                <?php foreach ($availableLocales as $locale => $localeDisplay): ?>
                <option value="<?= $locale?>"><?= $localeDisplay ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <?php endif; ?>
    </div>
    <div ng-show="isLoading" class="angular-ui-tree-loading text-center">
        <i class="fa fa-spin fa-refresh"></i>
    </div>
    <div ng-hide="isLoading" class="dd" ui-tree="treeOptions" data-drag-enabled="false">
        <ol class="dd-list" ui-tree-nodes="" ng-model="sitemap" id="tree-root">
            <li class="dd-item dd3-item" ng-repeat="item in sitemap" ui-tree-node ng-include="'link/sitemap/node.html'" ng-show="visible(item)"></li>
        </ol>
    </div>
</div>
